# Generated by Django 3.0.5 on 2020-04-06 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 34, 28, 960838, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='theme',
            field=models.CharField(max_length=60),
        ),
    ]
