# Generated by Django 3.0.5 on 2020-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20200406_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='theme',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
