# Generated by Django 3.0.5 on 2020-04-06 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20200406_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 35, 11, 475406, tzinfo=utc), verbose_name='date published'),
        ),
    ]
